dist: trusty
language: php
sudo: required

php:
  - 5.6

services:
  - docker

branches:
  except:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script: SQL_HOST=no ./deploy.sh -D -P && ./phar.sh "hlsdownload.phar" && ./gitci.sh "build/hlsdownload.phar" "Update build [skip ci]"
